Vagrant.configure("2") do |config|
  base_ip = 10
  1.upto(6) do |number|
    vmname = "node-#{"%02d" % number}"
    config.vm.define vmname do |instance|
      instance.vm.box = "ubuntu/bionic64"
      instance.vm.hostname = vmname
      instance.vm.network "private_network", ip: "192.168.33.#{base_ip + number}"
      instance.vm.provider "virtualbox" do |v|
        v.memory = 256
        v.cpus = 1
      end
    end
  end
  config.vm.define "ansible-host" do |instance|
      instance.vm.box = "ubuntu/bionic64"
      instance.vm.hostname = "ansible-host"
      instance.vm.network "private_network", ip: "192.168.33.#{base_ip+50}"
      instance.vm.provision "shell", inline: <<-EOF
      which ansible || ( apt update \
        && apt install -y software-properties-common \
        && apt-add-repository --yes --update ppa:ansible/ansible \
        && apt install -y ansible )
    EOF
  end
end
